# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - ".github"
  - ".vscode"
  - "assets/**/*"
  - "data/**/*"
  - "docs/**/*"
  - "model/**/*"
  - "postman_collections/**/*"
  - "swagger/**/*"
  - "tests/**/*"
  - ".gitignore"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.png"
  - "**/*.svg"
  - "go.mod"
  - "go.sum"
  - "LICENSE"
  - "main.go"
  - "README.md"
