exclude_paths:
  - ".github"
  - ".vscode"
  - "controllers/**/*"
  - "data/**/*"
  - "docs/**/*"
  - "models/**/*"
  - "postman_collections/**/*"
  - "routes/**/*"
  - "services/**/*"
  - ".gitignore"
  - "codecov.yml"
  - "go.mod"
  - "go.sum"
  - "LICENSE"
  - "main.go"
  - "README.md"
