# CodeRabbit Configuration
# Optimized for Go 1.25 / Gin RESTful API project

language: en-US
early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: true
  poem: false
  abort_on_close: true

  # Path-based review instructions for this Go/Gin project
  path_instructions:
    - path: "**/*.go"
      instructions: |
        - Follow idiomatic Go naming conventions (camelCase for unexported, PascalCase for exported)
        - Ensure proper error handling (always check and handle errors)
        - Verify package documentation comments exist
        - Check imports are grouped: standard library, then third-party, then local
        - Validate proper use of goroutines and channels if concurrency is used
        - Ensure defer statements are used appropriately
        - Check that CGO_ENABLED=1 is considered for SQLite operations

    - path: "controller/**/*.go"
      instructions: |
        - Controllers should be thin - delegate to services
        - Verify Swagger/OpenAPI annotations are present and complete
        - Check proper HTTP status codes (200, 201, 204, 404, 409)
        - Ensure functions use Go's (T, error) multiple-return pattern for fallible operations and errors are handled by callers
        - Validate that request/response models are used (not internal entities)
        - Check that Gin context is used properly (c.JSON, c.Status, etc.)

    - path: "service/**/*.go"
      instructions: |
        - Services should contain business logic
        - Verify GORM operations are used (no raw SQL)
        - Check proper error propagation to controllers
        - Ensure thread-safe operations with Mutex when needed
        - Validate business rules (e.g., unique squad numbers)

    - path: "route/**/*.go"
      instructions: |
        - Route configuration should be clean and organized
        - Verify cache middleware is applied to GET endpoints
        - Check ClearCache wrapper is used for POST/PUT/DELETE
        - Ensure path constants are defined in path.go
        - Validate proper route grouping and organization

    - path: "data/**/*.go"
      instructions: |
        - Verify GORM database connection is properly configured
        - Check SQLite driver is properly initialized
        - Ensure database connection uses proper connection pooling
        - Validate error handling during database initialization

    - path: "model/**/*.go"
      instructions: |
        - Use Go struct tags for serialization (e.g., `json:"fieldName"`)
        - Verify camelCase JSON serialization with struct tags
        - Check separation of internal (Player) vs API models (PlayerRequest/Response)
        - Ensure proper GORM struct tags for database mapping
        - Validate ID generation logic for auto-increment

    - path: "tests/**/*.go"
      instructions: |
        - Tests should use testify for assertions
        - Verify test naming follows Test<Method><Scenario>Response<Expected> pattern
        - Check Given-When-Then/AAA structure
        - Ensure test database uses in-memory SQLite
        - Validate test data is loaded from tests/players.json
        - Check coverage targets (80% for services, controllers, routes)

    - path: "**/*_test.go"
      instructions: |
        - Unit tests should use testify for assertions
        - Follow Test<FunctionName><Scenario> naming convention
        - Use table-driven tests for multiple test cases
        - Use external test packages (package_name_test) for black-box testing, or same package for white-box testing
        - Mock external dependencies appropriately
        - Test both success and error paths

    - path: "main.go"
      instructions: |
        - Verify proper database connection on startup
        - Check Gin router setup and configuration
        - Ensure graceful error handling (fail-fast on critical errors)
        - Validate server configuration (port 9000, localhost binding)

    - path: "docs/**"
      instructions: |
        - These are auto-generated by swag - DO NOT EDIT MANUALLY
        - Ensure docs are regenerated after controller annotation changes (swag init)

    - path: "swagger/**/*.go"
      instructions: |
        - Verify Swagger configuration is correct
        - Check API metadata (title, description, version)
        - Ensure proper host and schemes are configured

    - path: "**/Dockerfile"
      instructions: |
        - Verify multi-stage build (builder + runtime)
        - Check Go version matches project (1.25)
        - Ensure CGO dependencies are installed (gcc, musl-dev, sqlite-dev)
        - Validate non-root user is used for security
        - Check HEALTHCHECK instruction is present
        - Ensure CGO_ENABLED=1 during build for SQLite support

    - path: "go.mod"
      instructions: |
        - Verify Go version is 1.25
        - Check dependencies are up to date
        - Ensure replace directives are justified
        - Validate module path is correct

  # Ignore patterns for this project
  path_filters:
    - "!**/vendor/**"
    - "!**/storage/**"
    - "!**/*.db"
    - "!**/*.db-shm"
    - "!**/*.db-wal"
    - "!**/coverage.out"
    - "!**/docs/docs.go"
    - "!**/docs/swagger.json"
    - "!**/docs/swagger.yaml"

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
    drafts: false
    base_branches:
      - master
      - main

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 75
    title:
      mode: warning
      requirements: |
        - Use Conventional Commits format (feat:, fix:, chore:, docs:, test:, refactor:)
        - Keep under 80 characters
        - Be descriptive and specific
    description:
      mode: warning
    issue_assessment:
      mode: warning

  tools:
    # Relevant tools for Go projects
    golangci-lint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    hadolint:
      enabled: true
    yamllint:
      enabled: true
    actionlint:
      enabled: true
    semgrep:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 120000
    dotenvLint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true
    shellcheck:
      enabled: true

    # Disable irrelevant tools for Go project
    ruff:
      enabled: false
    biome:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    detekt:
      enabled: false
    eslint:
      enabled: false
    flake8:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    pmd:
      enabled: false
    clang:
      enabled: false
    cppcheck:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    prismaLint:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    htmlhint:
      enabled: false
    languagetool:
      enabled: false
    circleci:
      enabled: false
    fortitudeLint:
      enabled: false

chat:
  art: true
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - "**/Dockerfile"
      - "**/*.yml"
      - "**/*.yaml"
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
  mcp:
    usage: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "**/*.go"
        instructions: |
          - Use Go doc comments (// Package/Function name ...)
          - Place package documentation in package-level doc comment
          - Document exported functions, types, and methods
          - Keep documentation concise and focused
          - Include Swagger annotations for controller functions
  unit_tests:
    path_instructions:
      - path: "tests/**/*.go"
        instructions: |
          - Use testify framework for assertions
          - Follow Test<Method><Scenario>Response<Expected> naming
          - Use Given-When-Then or AAA structure with comments
          - Create test fixtures in separate files (e.g., player_fake.go)
          - Use in-memory SQLite for test database
          - Target 80% coverage for controllers, services, and routes

issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels:
        - planning
  labeling:
    labeling_instructions: []
    auto_apply_labels: false
