# Codacy Configuration
# Goal: 80% minimum coverage on service/, controller/, route/ only

exclude_paths:
  - ".github/**/*"
  - ".vscode/**/*"
  - "data/**/*"
  - "docs/**/*"
  - "model/**/*"
  - "postman-collections/**/*"
  - "scripts/**/*"
  - "storage/**/*"
  - "swagger/**/*"
  - "tests/**/*"
  - "main.go"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.md"

coverage:
  status:
    project:
      default:
        target: 80%
