services:
  api:
    image: go-samples-gin-restful
    container_name: gin-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - storage:/storage/
    environment:
      - STORAGE_PATH=/storage/players-sqlite3.db
      - GIN_MODE=release
    restart: unless-stopped

volumes:
  storage:
    name: go-samples-gin-restful_storage
